---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: pivotalservices/docker-concourse-cf-tools
    tag: "latest"

inputs:
- name: demo-onlinestore-order

outputs:
- name: current-app-info

run:
  path: demo-onlinestore-order/ci/tasks/get-currentapp.sh